// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1kRfNwoXVUTcEzX32RSl_p_FKSI42xU',
    appId: '1:560801349976:web:7f67de8358ac901780652d',
    messagingSenderId: '560801349976',
    projectId: 'grozar',
    authDomain: 'grozar.firebaseapp.com',
    databaseURL: 'https://grozar-default-rtdb.firebaseio.com',
    storageBucket: 'grozar.firebasestorage.app',
    measurementId: 'G-CDR95J2FF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OQebKf57g9RzpRoS25xsA0VBCyfMjJ8',
    appId: '1:560801349976:android:1f69c7a14eee4a5080652d',
    messagingSenderId: '560801349976',
    projectId: 'grozar',
    databaseURL: 'https://grozar-default-rtdb.firebaseio.com',
    storageBucket: 'grozar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WTMJgEOSFWUCCnco43W9gc2dhVyL9YQ',
    appId: '1:560801349976:ios:4f4f73c956a9f93080652d',
    messagingSenderId: '560801349976',
    projectId: 'grozar',
    databaseURL: 'https://grozar-default-rtdb.firebaseio.com',
    storageBucket: 'grozar.firebasestorage.app',
    iosClientId: '560801349976-obrheu92uv2a0tfidnkn3uu7je079qja.apps.googleusercontent.com',
    iosBundleId: 'com.datingapp.talk24loves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WTMJgEOSFWUCCnco43W9gc2dhVyL9YQ',
    appId: '1:560801349976:ios:4f4f73c956a9f93080652d',
    messagingSenderId: '560801349976',
    projectId: 'grozar',
    databaseURL: 'https://grozar-default-rtdb.firebaseio.com',
    storageBucket: 'grozar.firebasestorage.app',
    iosClientId: '560801349976-obrheu92uv2a0tfidnkn3uu7je079qja.apps.googleusercontent.com',
    iosBundleId: 'com.datingapp.talk24loves',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1kRfNwoXVUTcEzX32RSl_p_FKSI42xU',
    appId: '1:560801349976:web:f0322a16427fb1d380652d',
    messagingSenderId: '560801349976',
    projectId: 'grozar',
    authDomain: 'grozar.firebaseapp.com',
    databaseURL: 'https://grozar-default-rtdb.firebaseio.com',
    storageBucket: 'grozar.firebasestorage.app',
    measurementId: 'G-F96H7S5XZG',
  );
}
